// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations : connexion DIRECTE (port 5432). Sur Vercel, DATABASE_URL
    // pointe sur le pooler (6543, transaction mode) qui ne supporte pas les
    // migrations — on utilise donc DIRECT_URL si défini, sinon DATABASE_URL.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
